# update changelog after commit with --no-verify to avoid endless loop
- id: recreate-changelog
  name: recreate-changelog
  entry: Rscript inst/hooks/recreate_changelog.R
  language: r
  always_run: true
  stages: [post-commit]
